### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by keerockl**
Added security issues comment.

### CODE REVIEW

**Comment by keerockl** [comment]
holding for a moment.

**Comment by keerockl** [comment]
reopening after verification

**Comment by keerockl** [comment]
holding again

**Comment by andrew-elder** [comment]
Why wouldn't security issues be reported as issues to this github repo?

**Comment by keerockl** [comment]
Initial intention is to comply with Intel SDL process. we can reword it as below.

# Security issues

Please report any security issues with this code to https://github.com/AVnu/libavtp/issues

**Pull request closed without merging**
